<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite01" duration-ms="10816" started-at="2022-01-04T11:07:20Z" finished-at="2022-01-04T11:07:31Z">
    <groups>
      <group name="quick">
        <method signature="Validate_ContactUs.TC02(java.lang.reflect.Method)[pri:2, instance:testCases.Validate_ContactUs@14f9390f]" name="TC02" class="testCases.Validate_ContactUs"/>
        <method signature="Validate_ContactUs.TC03(java.lang.reflect.Method)[pri:3, instance:testCases.Validate_ContactUs@14f9390f]" name="TC03" class="testCases.Validate_ContactUs"/>
        <method signature="Validate_HomePage.TC01(java.lang.reflect.Method)[pri:1, instance:testCases.Validate_HomePage@258d79be]" name="TC01" class="testCases.Validate_HomePage"/>
      </group> <!-- quick -->
    </groups>
    <test name="test homepage" duration-ms="10816" started-at="2022-01-04T11:07:20Z" finished-at="2022-01-04T11:07:31Z">
      <class name="testCases.Validate_ContactUs">
        <test-method status="PASS" signature="gotoContactUsPage()[pri:0, instance:testCases.Validate_ContactUs@14f9390f]" name="gotoContactUsPage" is-config="true" duration-ms="9201" started-at="2022-01-04T16:37:21Z" finished-at="2022-01-04T16:37:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gotoContactUsPage -->
        <test-method status="PASS" signature="TC02(java.lang.reflect.Method)[pri:2, instance:testCases.Validate_ContactUs@14f9390f]" name="TC02" duration-ms="167" started-at="2022-01-04T16:37:30Z" finished-at="2022-01-04T16:37:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testCases.Validate_ContactUs.TC02(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02 -->
        <test-method status="SKIP" signature="TC03(java.lang.reflect.Method)[pri:3, instance:testCases.Validate_ContactUs@14f9390f]" name="TC03" duration-ms="184" started-at="2022-01-04T16:37:30Z" finished-at="2022-01-04T16:37:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testCases.Validate_ContactUs.TC03(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testCases.Validate_ContactUs.TC03(Validate_ContactUs.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
        <test-method status="SKIP" signature="TC03(java.lang.reflect.Method)[pri:3, instance:testCases.Validate_ContactUs@14f9390f]" name="TC03" duration-ms="104" started-at="2022-01-04T16:37:30Z" finished-at="2022-01-04T16:37:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testCases.Validate_ContactUs.TC03(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testCases.Validate_ContactUs.TC03(Validate_ContactUs.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
        <test-method status="FAIL" signature="TC03(java.lang.reflect.Method)[pri:3, instance:testCases.Validate_ContactUs@14f9390f]" name="TC03" duration-ms="106" started-at="2022-01-04T16:37:31Z" finished-at="2022-01-04T16:37:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testCases.Validate_ContactUs.TC03(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testCases.Validate_ContactUs.TC03(Validate_ContactUs.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
      </class> <!-- testCases.Validate_ContactUs -->
      <class name="testCases.KickOFF">
        <test-method status="PASS" signature="initDriver()[pri:0, instance:testCases.KickOFF@5a9f4771]" name="initDriver" is-config="true" duration-ms="17219" started-at="2022-01-04T16:37:03Z" finished-at="2022-01-04T16:37:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="PASS" signature="destroy()[pri:0, instance:testCases.KickOFF@5a9f4771]" name="destroy" is-config="true" duration-ms="821" started-at="2022-01-04T16:37:31Z" finished-at="2022-01-04T16:37:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- destroy -->
      </class> <!-- testCases.KickOFF -->
      <class name="testCases.Validate_HomePage">
        <test-method status="PASS" signature="TC01(java.lang.reflect.Method)[pri:1, instance:testCases.Validate_HomePage@258d79be]" name="TC01" duration-ms="12" started-at="2022-01-04T16:37:21Z" description="this is test 001" finished-at="2022-01-04T16:37:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testCases.Validate_HomePage.TC01(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01 -->
      </class> <!-- testCases.Validate_HomePage -->
    </test> <!-- test homepage -->
  </suite> <!-- Suite01 -->
</testng-results>
